### ISSUE TITLE
Reduce login time if possible...

### ISSUE THREAD

**Issue by divya21raj** [divya21raj/UniPool#41]
Takes a lot of time on slow connections

**Comment by ans24us1** [comment]
Why not open a session for the users and keep them logged in, instead of authenticating every time app opens. We can keep the information stored on local device in persistent app memory. Every month clear the contents and request for authentication. Many apps use this feature to save login time.

**Comment by divya21raj** [comment]
That already happens, it's only the first( and only) time they login, that faces some issues sometimes...

**Comment by ans24us1** [comment]
Checking code. Will get back.
Add logout functionality for testing.

**Comment by divya21raj** [comment]
Uninstall the previous version before doing anything though...

**Comment by divya21raj** [comment]
Commit #98 solves it to a great extent.
