### ISSUE TITLE
App has trouble running directly through Android Studio

### ISSUE THREAD

**Issue by Rohan-Datta** [divya21raj/UniPool#47]
If the project is run on an external phone through Android Studio, the execution stops at Sign In Activity, while giving a error/status code of "10". This problem is NOT faced if the same program is turned into an apk and then, used as an installed application.

**Comment by divya21raj** [comment]
Check this guide...
https://developers.google.com/android/guides/client-auth

**Comment by atishayjain708** [comment]
I'm unable to replicate the problem. Is it occurring when you use the code from master? Can you share the error codes from the Android Monitor?

**Comment by divya21raj** [comment]
SOLVED!

1. Get your SHA key by following the steps mentioned in the second answer here- https://stackoverflow.com/questions/15727912/sha-1-fingerprint-of-keystore-certificate/35707540

2.Go to project settings of the Firebase project and add this key there.
